title = "birdr"
languageCode = "en-gb"
baseurl = "http://blog.birdr.co.uk/"

theme = "hugo-minimalist-theme"

[params]
    site_author = "Matthew Williams"
    site_description = "Following the development of birdr."
    location = "London"
    # All paths are relative to the baseurl. Put your files
    # somewhere in the static folder.
    avatar = "img/profile.jpg"
    header_background = "img/bg.jpg"
    header_title = "birdr"
    copyright = "Powered by [Hugo](http://gohugo.io)."

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = ""
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "birdrapp"
    gplus     = ""
